### PR TITLE
Added map compiler as tool

### PR DESCRIPTION
**Pull request by Oflameo**
This pull request is to fix the issue https://github.com/spring/SpringMapConvNG/issues/2 and to make it easier to start making maps.

### CODE REVIEW

**Comment by ashdnazg** [comment]
I think you have to add it to cmake as well and distribution/automatic compilation is another matter that has to be dealt with

**Comment by Oflameo** [comment]
Okay; Take 2!

**Comment by abma** [comment]
hint: https://github.com/Oflameo/spring/blob/b22445ce83d58472aeee11a19adfa2226ab4fce0/tools/CMakeLists.txt#L14

**Comment by abma** [comment]
FYI: https://springrts.com/phpbb/viewtopic.php?t=40175

**Pull request closed without merging**
