### PR TITLE
Allow paralyzers to damage features

### PR DESCRIPTION
**Pull request by sprunk**
Previously Feature[Pre]Damaged wasn't even called so no easy way to emulate.

### CODE REVIEW

**Comment by rtri** [comment]
?

Don't tell me ZK has frankenstein'ed combi-weapons that both damage and paralyze.

**Comment by ashdnazg** [comment]
They did for the past few years.
Makes good gameplay too

**Comment by sprunk** [comment]
ZK's issue can be solved by swapping the types (make the weapon deal normal damage and add extra paralyzer with Lua instead of the other way around).

However I think that it would still be elegant for the engine not to have such hardcoded limitations. If someone wants paralyzer not to damage wrecks they can replicate it with armorDefs or Lua.

After some thought this PR would need a bit more work first to have quality though: paralyzer needs to be passed to Feature[Pre]Damaged, this is a problem because either it gets appended last and becomes inconsistent with Unit[Pre]Damaged, or breaks backward compatibility.

**Comment by GoogleFrog** [comment]
Is anyone using Feature[Pre]Damaged? The only issue I see here is backwards compatibility, the engine should be more general when the gameside change for compatibility is a little extra in armordefs.

**Comment by rtri** [comment]
The proper generalization here will also affect Unit[Pre]Damaged and `CUnit` code that assumes damage is either/or.

**Comment by sprunk** [comment]
How about now?

Features now call Feature[Pre]Damaged when getting damaged by paralyzer weapons but otherwise there is no change (damage type is still Xor, features still do not lose health when getting paralyzer damage).

**Comment by carlosalfonso2014** [comment]
Thanks a lot!

**Pull request closed without merging**
