### PR TITLE
All whispers are visible in a replay

### PR DESCRIPTION
**Pull request by sprunk**

### CODE REVIEW

**Comment by ashdnazg** [comment]
I'm not sure I like this as a default - you shouldn't have access to a conversation between two people without being certain they know about it...

**Comment by ashdnazg** [comment]
I never knew whispers are even recorded in a demo. In any case, this won't help anything except making people speccheat in other ways.

**Comment by sprunk** [comment]
Who said it's just for spec cheating? Maybe I would like to learn how to play FFA by watching a high skill replay and seeing how pros ~~lie to each other~~ conduct diplomacy would be helpful.

I consider the current state of affairs a bug, because I think everything in a replay should be visible unless there is a good reason not to. I don't consider privacy a good reason in this case because whispers are already in the demo so anybody dedicated can extract them anyway. Possibly whispers shouldn't be recorded in the demo instead, but I think that would go against the point of a replay.

**Comment by lhog** [comment]
Please don't forget to cherry-pick into transition.

**Comment by abma** [comment]
as its stored in the replay file its IMHO correct to show it.

**Pull request merged**
