### PR TITLE
Add `GetCurrentCamera`, tableless `GetCameraState`

### PR DESCRIPTION
**Pull request by sprunk**
`Spring.GetCurrentCamera` returns the name of the current camera,
for example "ta" or "spring" (currently available under the `name`
key in the table returned by `Spring.GetCameraState`).

`Spring.GetCameraState` now accepts a boolean parameter; if it is
false then instead of allocating a table, it returns cam-specific
values onto the stack (use `GetCurrentCamera` first to know how to
interpret them; use `GetCamera{Position,Direction,FOV}` to get the
non-specific values from the base class). The returned values are:
  fps, rot -> oldHeight
  ta -> height, angle, flipped
  spring -> rx, ry, rz, dist
  free -> rx, ry, rz, vx, vy, vz, avx, avy, avz
  ov -> (nil)

### CODE REVIEW

**Comment by ashdnazg** [comment]
Hmm, I suspect it could also work to just push the name before the rest of the args. 
Lua has no problem if it needs to unpack too little or too many arguments.
No strong opinion though, just for you to consider, if you want this merged as it is, it's also ok.

**Comment by sprunk** [comment]
My aim with having a separate callout was to get this
```lua
local camtype = Spring.GetCurrentCamera()
if camtype == "spring" then
   local rx, ry, rz = Spring.GetCameraState(false)
   -- some logic
elseif camtype = "ta" then
   local height, angle, flipped = Spring.GetCameraState(false)
   -- some logic
end
```
rather than this

```lua
local camtype, p1, p2, p3 = Spring.GetCameraState(false)
-- crappy var names, no idea what they mean yet
if camtype == "spring" then
  -- some logic where p1-3 mean rotation x/y/z
elseif camtype == "ta" then
  -- some other logic in which p1-3 don't mean rotation x/y/z but height/angle/flipped
end
```

**Comment by ashdnazg** [comment]
I know, I just wanted to verify you thought of the second option, since afaik your aim here is optimisation, and 1 call is less than 2 calls.

**Comment by sprunk** [comment]
I added the camera name to `GetCameraState(false)`. I kept `GetCurrentCamera` but am ambivalent about it now.

**Comment by ashdnazg** [comment]
haha, never knew design by committee can happen with 2 people

**Pull request merged**
