### PR TITLE
fix SetDecalAlpha

### PR DESCRIPTION
**Pull request by sprunk**

### CODE REVIEW

**Comment by ashdnazg** [comment]
ty

**Comment by gajop** [comment]
Wait a minute, does decalsGl4 actually work? I thought it was unused

**Comment by ashdnazg** [comment]
I'm not sure, but the error was an error nevertheless

**Comment by gajop** [comment]
I agree of course, but due to https://github.com/sprunk/spring/blob/d17d18bf616aec93d847a9cecf50df3f97fb20e5/rts/Rendering/Env/IGroundDecalDrawer.cpp#L27-L36 I think it is disabled. Was wondering if someone was using it and ran into this problem or not, @sprunk ?

**Comment by sprunk** [comment]
No, I just saw it in the code.

**Comment by gajop** [comment]
Okey, thanks

**Pull request merged**
