### PR TITLE
[AI] Only istream gets reset, not ostream. Safe aiSize for CregLoadSave

### PR DESCRIPTION
**Pull request by rlcevg**
ostream is an output, it doesn't seem logical to reset output in streamCopy (SkirmishAIWrapper.cpp)

Actually resetting istream after each AI started to use own load-stream is actually pointless with current usage. But still streamCopy, if it's really "copy", shouldn't change input in theory.

Edit: I should have probably mention earlier that this is not an enhancement, but a bug fix.
Currently each subsequent AI saves all previous data plus its own. Save/Load is broken.

### CODE REVIEW

**Comment by ashdnazg** [comment]
'\n' in a binary file seems a bit out of place
How about calling SerializeInt?

**Comment by rlcevg** [comment]
I agree.
To my surprize ```oss << aiSize;``` writes aiSize in text mode (maybe it can be changed through stream configuration, don't know).
SerializeInt is the better way. How to do it? Or if you know, simply override/disregard my '\n' changes.

**Comment by ashdnazg** [comment]
SerializeInt won't help as it's in the OutputStreamSerializer :S

**Comment by rlcevg** [comment]
Why not? Simply combine 2 blocks ```// save creg state``` and ```// save AI state```, that way os (creg::COutputStreamSerializer) will be still reachable.

**Comment by ashdnazg** [comment]
I haven't slept much tonight, seems to affect my creativity :)

**Pull request merged**
