### PR TITLE
GL4 changes in UI and font rendering

### PR DESCRIPTION
**Pull request by pts1667**
Here I put some GL4 changes. Note that I made some changes before forking so I may have lost some files (but most likely and hopefully not). I tried to test my changes with the very latest state of the repo, but unfortunately I seem to be getting SIGFPE signals with sound? The PR worked with the earlier version (12 hours ago) of the repo well:
https://springrts.com/phpbb/viewtopic.php?f=11&t=36843

I hope this is useful. I tried to get the main menu display working as it seems the general strategy as described in the forums seems to be get stuff working -> see what's removed in the core profile and work on that next? I hope this is up to code standards, and apologies if not.

### CODE REVIEW

**Comment by abma** [comment]
with this changes, this springsettings.cfg:

ForceCoreContext = 1
GLContextMajorVersion = 4

and http://paste.springfiles.com/view/raw/a1618954

this makes the menu work for me, too.

**Comment by rtri** [comment]
Hi, thanks for contributing. I have just two remarks:

* the PushAttrib's can not be removed until all font callers are known to be isolated from its state changes, not just the startup menu (doing this requires a state tracker which is underway)
* depth-testing may or may not be safe to leave disabled for all call sites, for now it's best not to touch seemingly redundant bits

    > the general strategy as described in the forums seems to be get stuff working -> see what's removed in the core profile and work on that next?

It's not quite so unguided, but you can certainly take that approach to get familiar.

**Comment by rtri** [comment]
:+1:

**Comment by rtri** [comment]
:+1: 

edit: some minor artefacts have popped up in text rendering now, could you please take a look at these?

sscr0
sscr1

**Comment by pts1667** [comment]
I'll try but right now I can't seem to get the game running at all. Something to do with sigfpe exceptions in OpenAL? Anyway once I get the game running again I'll try to fix it. Looks like something's wrong with rendering spaces, presumably the text shadows.

**Pull request merged**
