### PR TITLE
Rifle weapontype: remove hardcoded particles

### PR DESCRIPTION
**Pull request by sprunk**
I don't think anybody is using Rifles (harcoded low-quality particles being one of the reasons!) so this should do no harm and is fairly easy to replicate with Lua. On the other hand, Rifle could become more useful as a very simple hitscan weapon (simpler than BeamLaser which still involves a projectile).

### CODE REVIEW

**Comment by silentwings** [comment]
iirc rifles are used for snipers in some *A games

**Comment by sprunk** [comment]
Not in BA: https://github.com/Balanced-Annihilation/Balanced-Annihilation/blob/master/units/ArmKbots/T2/armsnipe.lua#L154

Not in BAR: https://github.com/beyond-all-reason/Beyond-All-Reason/blob/master/units/ArmKbots/T2/armsnipe.lua#L157

Not in TechA: https://github.com/nixtux/TA/blob/master/units/armsnipe.lua#L122

Not in ZK: https://github.com/zerok-rts/zero-k/blob/master/units/cloaksnipe.lua#L114

**Comment by sprunk** [comment]
Not BA(R).

I can't find a TechA repo, I found https://github.com/n3wm1nd/TA which does have Rifles but that one was last updated in 2016 so would already be broken by the myriad engine changes since then.

**Comment by abma** [comment]
techa is at https://github.com/techannihilation/TA

**Comment by sprunk** [comment]
Alright, so TechA uses Rifle - it would probably be good to wait with this patch for goodwill reasons then. At some point I might submit a patch to make Rifle support CEGs which would make it easier to replicate those particles.

**Pull request merged**
