### PR TITLE
Manual unit share: allow EMPed units

### PR DESCRIPTION
**Pull request by sprunk**
The decision to block this belongs to the mod.

### CODE REVIEW

**Comment by ashdnazg** [comment]
What will happen if you gave a nanoframe inside a factory while keeping the factory?

**Comment by sprunk** [comment]
I suspect nothing but for safety I changed the PR to only unblock EMPed unit transfer (because this is safe).

**Comment by ashdnazg** [comment]
thanks!

there should probably be an "AllowGive" callin

**Comment by sprunk** [comment]
There is an AllowUnitTransfer call-in already.

**Comment by ashdnazg** [comment]
ah, good.

**Pull request merged**
