### PR TITLE
Cannon: Use autoTargetRangeBoost when set

### PR DESCRIPTION
**Pull request by esainane**
Resolves mantis #6382: https://springrts.com/mantis/view.php?id=6382

### CODE REVIEW

**Comment by esainane** [comment]
I'm not sure what the best way to create a sister PR for the maintenance branch is. Should I make a merge commit, or just cherry-pick it?

**Comment by ashdnazg** [comment]
don't make sister PR, this will be cherry-picked after merging

**Comment by gajop** [comment]
For reference, this is the original commit that introduced the unused boost variables (perhaps on purpose): https://github.com/spring/spring/commit/15d6cc6661b00ebd5650308b3d723e9ae3a21047

If you add it to Cannon, you may as well add it to StarburstLauncher?

Other than that, seeing as 0 is the default I think this could be merged. 
So you have a very weak accept from me if you apply the same thing to the StartburstLauncher

**Comment by esainane** [comment]
Added!

**Comment by gajop** [comment]
@esainane Ah.. I forgot to ask, but can you update the changelog too please?

**Comment by esainane** [comment]
Would something like the following in the lua section of doc/changelog.txt be appropriate?

```
 - Spring.SetUnitWeaponState with "autoTargetRangeBoost" now also lets Cannon
   and StarburstLauncher weapons look ahead and pre-aim at targets just
   outside of nominal range.
```

**Comment by gajop** [comment]
I suppose that's fine

**Comment by esainane** [comment]
Added it in. Any suggestions if the wording could be improved would be more than welcome, of course!

**Pull request merged**
