### PR TITLE
AllowStartPosition now receives 9th parameter teamID

### PR DESCRIPTION
**Pull request by sprunk**
Useful for AIs who always report playerID 255 (also convenience)

### CODE REVIEW

**Comment by rtri** [comment]
I think it's better to just bite the bullet and sanitize `gadget:AllowStartPosition`'s parameter order.

**Comment by rtri** [comment]
That's fine.

**Comment by sprunk** [comment]
So what should the order be?
`playerID, teamID, readyState, real xyz, clamped xyz` ?

**Comment by rtri** [comment]
The same as the engine's internal order: player, team, ready, clamped, raw.

**Comment by rtri** [comment]
looks good, thanks.

**Pull request merged**
