### PR TITLE
Fix #1382, draw calls see too much under ceasefire

### PR DESCRIPTION
**Pull request by sprunk**

### CODE REVIEW

**Comment by ashdnazg** [comment]
I suspect you haven't tested it locally, and this is the kind of change that might have loads of unintended consequences, so until someone tests this, the PR will wait

**Comment by ashdnazg** [comment]
The engine seems quite in conflict with itself whether you should or shouldn't see units of ceasefired allyteams:
https://github.com/spring/spring/blob/develop/rts/Sim/Units/Unit.cpp#L1595

**Comment by sprunk** [comment]
This PR just makes LuaGL calls consistent with regular unit rendering by making it only look at the LOS_INLOS bit. Whether the engine is inconsistent about setting that bit is orthogonal IMO.

**Comment by ashdnazg** [comment]
so it should just remove the entire allycheck variable...

**Pull request merged**
