### PR TITLE
Update Lock free lua

### PR DESCRIPTION
**Pull request by ashdnazg**

### CODE REVIEW

**Comment by abma** [comment]
whats the purpose of updating this branch? will it ever be merged into develop? if not i'll vote for deleting this branch.

**Comment by ashdnazg** [comment]
The purpose of this branch is to test and gather data so an informed decision about merging it to develop can be made.

**Comment by abma** [comment]
> The purpose of this branch is to test and gather data

isn't https://docs.google.com/spreadsheets/d/15dq0EuuhB29ezifaOQIu2PMpR9T7hbpeGGmgqMPGACI/edit#gid=2064064053 enough?

what else data do you want to collect? i miss the discussion here.

**Comment by ashdnazg** [comment]
That's objective benchmarking data which can be gathered (and was gathered) without any branch.
This branch (and automatic builds) allow tests on multiple machines by multiple users and may give us an ultimate answer whether the 10v10s have desirable performance and the ZK people can finally migrate from 91.0, which can only be given by actually playing said 10v10s.

I don't want to find myself trying to argue for merging this change without being sure ZK will migrate as a result (it will be a waste of everybody's time if they don't).

**Comment by abma** [comment]
afaik this change requires dropping LoadingMT = 1

**Comment by abma** [comment]
testUnitSync fails:
http://buildbot.springrts.com/builders/validationtests/builds/4511/steps/test/logs/stdio

**Pull request merged**
