### PR TITLE
Add `isSubmarine` to unitdefs' movedef subtable

### PR DESCRIPTION
**Pull request by sprunk**

### CODE REVIEW

**Comment by lhog** [comment]
Is this one needed/wanted still?

**Comment by sprunk** [comment]
Yes but it should probably be PR'd to `transition` instead, and/or to BAR.

**Comment by lhog** [comment]
I'm unsure either. I guess the final decision is on Kloot as the one who put tremendous effort in spring in general and on develop specifically.

**Comment by rtri** [comment]
FTR I don't anticipate much non-rendering work being done for the foreseeable future, so for PR's following the usual develop->transition path is fine for now.

**Pull request merged**
