### PR TITLE
Reopening of Ivand's PR to merge back BAR branch into spring/transition

### PR DESCRIPTION
**Pull request by springraaar**
Hi

This is a reopening of   [ivand's PR to merge a stable iteration of the BAR engine into the transition branch](https://github.com/spring/spring/pull/559).

### CODE REVIEW

**Review by gajop — APPROVED** [review]
LGTM!

**Comment by sprunk** [comment]
Suffers from a lack of changelog

**Comment by lhog** [comment]
@springraaar I appreciate your effort, but the PR was closed not only because of the lack of the feedback, but because BAR branch doesn't make sense anymore. It's yesterday's (in fact several months old) news. If someone issues a request for change here, I'm not going to do it, nor I recommend anyone to do.

What you could do instead is you should clone BAR105, that has GP4 Unit/Feature Rendering, MT Pathfinder, tons of other fixes, and PR it. What you do here is nearly useless.

I don't know why you can't trust the author's decision to close PR to the irrelevant branch.

**Comment by Are-s** [comment]
please dont merge this unless kloot approves

**Comment by springraaar** [comment]
I did clone both branches.

comparing with a clone I had of the maintenance branch used for 105.0 and should be very close to the transition branch, it seems that the number of differences between the BAR105 branch and the transition branch are indeed just slightly bigger than between the PR branch and the transition branch:

git diff --stat maintenance..BAR105
 407 files changed, 101954 insertions(+), 1807 deletions(-)

git diff --stat maintenance..BARpr
 380 files changed, 100456 insertions(+), 1362 deletions(-)


but also that the number of lines changed between the BARpr and BAR105 is relatively small and probably much easier to digest:

git diff --stat BARpr..BAR105
145 files changed, 1895 insertions(+), 842 deletions(-)

The reviewing of BARpr's code on the other PR was also halfway done. It might be easier to merge that first and then merge the BAR105 next?

I don't know. [This](https://github.com/spring/spring/pull/559#issuecomment-911565140) comment indicates some fatigue dealing with the recurring changes.

**Pull request closed without merging**
