### PR TITLE
Remove random undocumented beamlaser range modifer

### PR DESCRIPTION
**Pull request by sprunk**
Remove beamlaser 30% range boost on mobile units.
~~Remove beamlaser -5% range penalty when FPSed.~~

### CODE REVIEW

**Comment by GoogleFrog** [comment]
The -5% is because you can FPS units to fire slightly beyond their range or graze the edge of hitvolumes of units which are technically not in range. This is most important when a turret is involved.

I agree with removing the +30% for mobile units. You can overshoot with inaccurate weapons force fired at the ground or poorly placed enemy units.

**Comment by sprunk** [comment]
Grazing out-of-range hitvolumes will always be a problem as long as targetBorder < 1.0 and disappears with targetBorder = 1.0; for any range reduction value and targetBorder pair you can give a range and hitvolume radius pair that allows grazing, which is any hit radius larger than ((1-reduction) / (1-targetBorder))*range. This is related to the weapondef's targetBorder setting and unrelated to FPS (would be possible to do with normal orders too if you could give an attack order in the air - it can possibly even be reproduced now for certain setups).

GoogleFrog how recently have you checked it for turrets specifically? When BA disallowed FPSing turrets the 130% was for every beamlaser (ie. turrets too) and there was no 95% override for FPS; the +30% was the cause for range hax.

**Comment by sprunk** [comment]
Updated to only remove the +30% for mobiles.

**Comment by sprunk** [comment]
Looks like not happening.

**Pull request closed without merging**
