### PR TITLE
Get*Info(id, false) -> no customkeys table alloc

### PR DESCRIPTION
**Pull request by sprunk**

### CODE REVIEW

**Comment by rtri** [comment]
Why aren't you pushing `nil` in `GetPlayerInfo` as well?

**Comment by sprunk** [comment]
Why? That would break every existing widget that uses either the table or the multiplier.

**Comment by rtri** [comment]
1) API consistency with `GetPlayerInfo`
2) anyone wanting to take advantage of this (which should be everybody maintaining an active project) will have to adjust calls regardless, two birds one stone etc

**Comment by sprunk** [comment]
It is done.

**Comment by rtri** [comment]
ty

**Pull request merged**
