### PR TITLE
added lua override for infomaps

### PR DESCRIPTION
**Pull request by enetheru**
added three more tags for the smf section of the mapinfo.lua file to override the type,metal and grass infomaps from greyscale images. if the file is missing or invalid dimensions a content_error exception will be thrown with an informative error message

### CODE REVIEW

**Comment by gajop** [comment]
As always with my useful comments: fix whitespace in rts/Map/MapInfo.h

**Comment by enetheru** [comment]
aww man i knew that would get me.. ive changed my vimrc so that i dont get caught out again.

**Comment by jk3064** [comment]
If you wonder why I didn't merged it yet, it's cause it adds a new dependency to spring-headless which needs to be explicitly added first.

**Comment by enetheru** [comment]
ooh ok. I don't know how that works. I guessed i would run into trouble with these ones since they should be synced.

**Pull request merged**
