### PR TITLE
Unhardcode leash distances

### PR DESCRIPTION
**Pull request by sprunk**

### CODE REVIEW

**Comment by ashdnazg** [comment]
maneuverLeash wasn't used in anything?

**Comment by sprunk** [comment]
It was only used here: https://github.com/spring/spring/blob/develop/rts/Sim/Units/CommandAI/MobileCAI.cpp#L665

**Comment by ashdnazg** [comment]
did you test how units behave afterwards?

**Comment by sprunk** [comment]
Not yet

**Comment by GoogleFrog** [comment]
I am worried that you have replaced many different magic numbers with one configurable value.  For example MobileCAI uses three different magic numbers and the difference between these numbers may have been important. A change like this should always implement the old behavior by default so I recommend using a new unitDef (because games will have deprecated tags hanging around in them) and preserving the ratio of  the magic numbers.

**Pull request closed without merging**
